name: Publish docs to Wiki

on:
  push:
#    paths:
#      - wiki/**
#    branches:
#      - main

env:
  USER_TOKEN: ${{ secrets.GH_PAT }}
  USER_NAME: "GitHub Actions"
  USER_EMAIL: "shymega@users.noreply.github.com"
  OWNER: shymega
  REPOSITORY_NAME: planet-devices

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add Wiki as a remote
        run: git remote add wiki https://$OWNER:$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki

      - name: Mirror all commits to production Wiki remote.
        run: git push --force wiki main:master

